//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 专业
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 专业()
        {
            this.学生 = new HashSet<学生>();
        }
    
        public int 专业编号 { get; set; }
        public string 专业名称 { get; set; }
        public Nullable<int> 所属院系 { get; set; }
        public string 备用字段1 { get; set; }
        public string 备用字段2 { get; set; }
        public string 备用字段3 { get; set; }
        public string 备用字段4 { get; set; }
        public string 备用字段5 { get; set; }
        public string 是否有效 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<学生> 学生 { get; set; }
        public virtual 院系 院系 { get; set; }
    }
}
