//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 学生
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 学生()
        {
            this.选课 = new HashSet<选课>();
        }
    
        public int 学生学号 { get; set; }
        public string 学生姓名 { get; set; }
        public int 学生性别 { get; set; }
        public int 学生年龄 { get; set; }
        public Nullable<int> 学生年级 { get; set; }
        public Nullable<int> 学生所属专业 { get; set; }
        public string 学生登录密码 { get; set; }
        public string 学生照片 { get; set; }
        public string 身份证号 { get; set; }
        public string 学生照片1 { get; set; }
        public string 学生照片2 { get; set; }
        public string 学生照片3 { get; set; }
        public string 学生照片4 { get; set; }
        public string 学生照片5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<选课> 选课 { get; set; }
        public virtual 专业 专业 { get; set; }
    }
}
