//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 时间
    {
        public int 各类开发时间编号 { get; set; }
        public string 时间名 { get; set; }
        public string 类名 { get; set; }
        public Nullable<System.DateTime> 开始时间 { get; set; }
        public Nullable<System.DateTime> 结束时间 { get; set; }
        public string 备用字段1 { get; set; }
        public string 备用字段2 { get; set; }
        public string 备用字段3 { get; set; }
        public string 备用字段4 { get; set; }
        public string 备用字段5 { get; set; }
        public string 是否有效字段 { get; set; }
    }
}
