//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 课程
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 课程()
        {
            this.选课 = new HashSet<选课>();
        }
    
        public int 课程编号 { get; set; }
        public string 课程名称 { get; set; }
        public Nullable<int> 授课老师 { get; set; }
        public Nullable<int> 学分 { get; set; }
        public string 课程分类 { get; set; }
        public Nullable<int> 限制人数 { get; set; }
        public string 开课对象 { get; set; }
        public string 上课时间 { get; set; }
        public string 上课地点 { get; set; }
        public string 课程简介 { get; set; }
        public string 课程图片 { get; set; }
        public Nullable<int> 院系编号 { get; set; }
        public int 课时 { get; set; }
        public string 备用字段1 { get; set; }
        public string 备用字段2 { get; set; }
        public string 备用字段3 { get; set; }
        public string 备用字段4 { get; set; }
        public string 备用字段5 { get; set; }
    
        public virtual 教师 教师 { get; set; }
        public virtual 院系 院系 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<选课> 选课 { get; set; }
    }
}
