//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 选课
    {
        public int 选课学生的学号 { get; set; }
        public int 学生所选课程的编号 { get; set; }
        public Nullable<double> 学生修课的成绩 { get; set; }
        public string 备用字段1 { get; set; }
        public string 备用字段2 { get; set; }
        public string 备用字段3 { get; set; }
        public string 备用字段4 { get; set; }
        public string 备用字段5 { get; set; }
    
        public virtual 课程 课程 { get; set; }
        public virtual 学生 学生 { get; set; }
    }
}
