//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 通知
    {
        public int 通知公告编号 { get; set; }
        public string 通知公告标题 { get; set; }
        public string 通知公告内容 { get; set; }
        public Nullable<System.DateTime> 通知公告发布时间 { get; set; }
        public Nullable<int> 公告发布员 { get; set; }
        public string 备用字段1 { get; set; }
        public string 备用字段2 { get; set; }
        public string 备用字段3 { get; set; }
        public string 备用字段4 { get; set; }
        public string 备用字段5 { get; set; }
    
        public virtual 管理员 管理员 { get; set; }
    }
}
