//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 院系
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 院系()
        {
            this.教师 = new HashSet<教师>();
            this.课程 = new HashSet<课程>();
            this.专业 = new HashSet<专业>();
        }
    
        public int 院系编号 { get; set; }
        public string 院系名 { get; set; }
        public Nullable<int> 院长 { get; set; }
        public string 备用字段1 { get; set; }
        public string 备用字段2 { get; set; }
        public string 备用字段3 { get; set; }
        public string 备用字段4 { get; set; }
        public string 备用字段5 { get; set; }
        public string 是否有效 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<教师> 教师 { get; set; }
        public virtual 教师 教师1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<课程> 课程 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<专业> 专业 { get; set; }
    }
}
